language: node_js

sudo: true

cache:
  apt: true

node_js:
  - "6"
  - "node"

before_install:
  - sudo chmod +x create-test.sh

install:
  - ./create-test.sh

script:
  - cd ./test
  - node ./index.js